eureka:
  client:
    register-with-eureka:
      value: false
    fetch-registry:
      value: false;
    service-url:
      defaultZone: http://discovery-eureka-server.herokuapp.com/
    instance:
      hostname: localhost
