eureka:
  client:
    register-with-eureka:
      value: true
    fetch-registry:
      value: true;
    service-url:
      defaultZone: https://discovery-eureka-server.herokuapp.com/
    instance:
      hostname: discovery-eureka-server.herokuapp.com

